src/WebApi_ws_live.cpp
webapp/src/types/LiveDataStatus.ts
webapp/src/views/HomeView.vue

Hide Victron Ve.direct UI elements from Live page when disabled

---

webapp/src/views/PowerMeterAdminView.vue

Fixed linting errors and removed some code oddities

webapp / yarn linting issues

---

include/PowerLimiter.h
src/PowerLimiter.cpp

A PR for the issue described here: https://github.com/helgeerbe/OpenDTU-OnBattery/issues/193
There is too much sunshine so I could not really test this. So please consider this draft for now

Inverter toggle fix

---

src/MqttHandleHuawei.cpp
src/MqttHandlePowerLimiter.cpp

fix: ignore MQTT messages for disabled components #203

---

README_onBattery.md

I drafted some documentation that describes the power limiter a) for other users and b) to offload me mentally when looking at the bugfix for https://github.com/helgeerbe/OpenDTU-OnBattery/issues/193
@helgeerbe I hope that I have understood it now but it would be good if you can crosscheck

Improved power limiter documentation

---

README.md
docs/Web-API.md

- fix vedirectlivedata typo
- add some more api urls

docs/Web-API.md: fix vedirectlivedata typo

---

docs/MQTT_Topics.md

explain DPL modes set through MQTT in more detail

---

src/PowerLimiter.cpp

DPL: do not use nullptr when printing debug messages

---

webapp/src/components/HuaweiView.vue

Fix for https://github.com/helgeerbe/OpenDTU-OnBattery/issues/267

Huawei PSU set values in floating point 

---

include/PowerLimiter.h
src/PowerLimiter.cpp

* avoid code duplication
* use load corrected voltage consistently
* remove the need for parameter of useFullSolarPassthrough()

DPL: use testThreshold() in useFullSolarPassthrough()

---

include/MqttHandlePylontechHass.h
include/MqttHandleVedirectHass.h
src/MqttHandlVedirectHass.cpp
src/MqttHandlePylontechHass.cpp

* add Icons for Battery and Victron device sensors in Home Assistant overriding the boring default icon for many sensors

Feature: add nice Icons for HA autoconfiguration

---

src/PowerLimiter.cpp

Channel for AC must always be CH0

---

src/MqttHandleVedirect.cpp

The added values P, IPV, and E, are calculated by OpenDTU-OnBatery and part of the web application live view, but were previously not published through MQTT.
Closes #376.

Publish calculated MPPT metrics

---

include/Huawei_can.h
webapp/src/views/AcChargerAdminView.vue

Reduces lower limit of AC-charger to 50W. In response to: 
https://github.com/helgeerbe/OpenDTU-OnBattery/issues/548

Reducing lower limit for AC-charger

---

README_onBattery.md

the DPL is described in more detail in the Wiki, which is the canonical source of information.
relates to #587.

remove description of DPL from README

---

include/HttpPowerMeter.h
platformio.ini
src/HttpPowerMeter.cpp

should resolve the connection refused issues reported in https://github.com/helgeerbe/OpenDTU-OnBattery/issues/611

fix to HttpPowermeter not using explicitly specified non standard ports

---

lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp

Fixes typos and errors, and adds previously unknown PIDs.
Closes #641.

Update VE.Direct product IDs

---

webapp/src/components/InverterTotalInfo.vue
webapp/src/views/HomeView.vue

Fix: copy OnBattery-specific data from live view websocket

---

include/PowerMeter.h
include/SMA_HM.h
src/PowerMeter.cpp
src/SMA_HM.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/views/PowerMeterAdminView.vue

Zum testen kann der SMA Simulator verwendet werden:
https://github.com/RalfOGit/sma-emeter-simulator
Nach Aktvierung über das Smartmeter Admin Menü, werden die Werte per Multicast Empfangen.

Integration SMA Homemanager 2.0 Final

---

src/SMA_HM.cpp

SMA HM 2.0:  Anpassung, dass Einspeisung negativen Wert ausgibt.

---

src/PowerLimiter.cpp

Vielen Dank @helgeerbe  für dein sehr hilfreiches und interessantes Projekt!
Es ist die Speicher- und Nulleinspeisungs-Lösung für Balkonkraftwerke u.ä, die ich derzeit am meisten empfehlen kann.
Ich habe es gestern [auf meiner Solarinfo-Seite beschrieben](https://ddvo.github.io/Solar/#OpenDTU-OnBattery).
Wenn du dazu Verbesserungshinweise hast, freue ich mich.
Beim Durchsehen der Implementierung in PowerLimiter.cpp fiel mir auf, dass die Code-Dokumentation zu :calcPowerLimit()`
etwas inkonsistent mit der Implementierung und etwas umständlicher ist als nötig.
Das schlage ich vor, wie folgt glattzuziehen.

PowerLimiter.cpp: simplification and minor correction of logic table comments

---

webapp/src/locales/de.json

Scheinbar hat sich mir hier ein kleiner Fehler eingeschlichen...

Fix german locales 

---

src/PowerLimiter.cpp

for solar-powered inverters, the unconditional full solar-passthrough implementation now sets the upper limit configured in the DPL settings.
Closes #900.

Fix: DPL mode 2 for solar-powered inverters

---

include/HttpPowerMeter.h
platformio.ini
src/Configuration.cpp
src/HttpPowerMeter.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/views/PowerMeterAdminView.vue

What a nice, incrementing date/version :blush: 
This release fixes the firmware for non-S3 devices (by reducing flash memory usage) and fixes a small issue with solar passthrough losses setting not being persisted.

Prepare Release 2024.05.06

---

src/PowerLimiter.cpp

It seems that the inverter does not react to shaded/limited inputs as we thought it would, see issue https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1087
I am trying to further improve the logic with this PR.
- ~input only needs 95% of the expected power to count as not-shaded~
- Always use newLimit if all channels are shaded and currentLimit is less than newLimit
- Respect '_verboseLogging' flag

chore: Improve overscaling for shaded inputs

---

src/WebApi_Huawei.cpp
src/WebApi_battery.cpp
src/WebApi_powermeter.cpp

Fixes https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1145 by adding the correct auth check on battery, huawei and powermeter API endpoints.

fix: add auth check on battery, huawei and powermeter API endpoints

---

src/PowerLimiter.cpp

I also created a PR in the upstream because it looks like there is a typo in `SunPosition`: https://github.com/tbnobody/OpenDTU/pull/2198

Fix DPL nighttime discharging: use SunPosition.isDayPeriod() to check if its day or night

---

src/PowerLimiter.cpp
src/WebApi_powerlimiter.cpp
webapp/src/views/PowerLimiterAdminView.vue

Changed settings view and powerlimiter to close https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1169

adjustment: allow use of 'use battery at night' without VE.Direct

---

src/Huawei_can.cpp

@LennartF22 I kindly request your comment on this, though I think this is indeed what you suggested in https://github.com/helgeerbe/OpenDTU-OnBattery/discussions/1309#discussioncomment-10855631.

Huawei CAN: use SpiManager to claim SPI bus

---

src/WebApi_sysstatus.cpp
webapp/src/components/TaskDetails.vue
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/types/SystemStatus.ts
webapp/src/views/SystemInfoView.vue

shows whether or not known tasks are alive, and in particular shows how much of the respective stack is still available.

Feature: show task details in system info view

---

lib/VeDirectFrameHandler/VeDirectData.cpp
lib/VeDirectFrameHandler/VeDirectData.h
lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
lib/VeDirectFrameHandler/VeDirectMpptController.cpp
src/MqttHandleVedirect.cpp
src/MqttHandleVedirectHass.cpp
src/WebApi_ws_vedirect_live.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json

- process the "RELAY" information from the charger
- add to live view
- add to MQTT and HASS
Note: Only processed if available. Not all charger contain a fault relais

Feature: Add VE.Direct "RELAY" to live view, MQTT, and HASS

---

include/WebApi_ws_Huawei.h
include/WebApi_ws_battery.h
include/WebApi_ws_console.h
include/WebApi_ws_live.h
include/WebApi_ws_solarcharger_live.h
platformio.ini
src/WebApi_ws_live.cpp

Thomas performed a second release yesterday with the same Git tag, after we already merged yesterday's first release. This changeset merges the updated Git tag.

Merge updated upstream tag v25.1.14

---

webapp/src/views/PowerLimiterAdminView.vue

| before | after |
|-------|-----|
|![Screenshot 2025-01-24 at 16 12 39](https://github.com/user-attachments/assets/50343586-f22f-4c98-9659-ddb0932eae40)|![Screenshot 2025-01-24 at 16 10 57](https://github.com/user-attachments/assets/34469fa9-c1f1-4593-908c-8076e2955fc0)|

webapp: set overscaling threshold default value

---

webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/views/PowerLimiterAdminView.vue

Closes https://github.com/hoylabs/OpenDTU-OnBattery/issues/1595

webapp: explain "Use battery at night.."

---

include/PowerLimiter.h
src/PowerLimiter.cpp
src/gridcharger/huawei/Controller.cpp

Fix: R48xx: only interlock against battery-powered inverters

---

src/battery/Controller.cpp

this change re-implements said function, using lambda functions inside it to allow for usage of return statements, which greatly improve readability.
closes #1657.

Fix: make getDischargeCurrentLimit() readable and return expected value

---

lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp

This should prevent MQTT disconnects from invalid utf-8 (https://github.com/hoylabs/OpenDTU-OnBattery/issues/1755) and help a bit (but can't prevent) phantom devices (https://github.com/hoylabs/OpenDTU-OnBattery/issues/1692) when the Ve.Direct connection is suffering from occasional bit errors.

VeDirectFrameHandler: Reject non-ascii characters

---

lib/VeDirectFrameHandler/VeDirectData.cpp

I did not found any official documentation from Victron.
See #1798

Add SmartShunt 300A/50mV to PID list

---

src/solarcharger/victron/Stats.cpp

the DPL shall use the VE.Direct network input power to derive (guesstimate) the available solar output. we did this before already, but a regression was introduced with the solar charger refactoring.
we now also try to be smarted about guesstimating the output: we reduce the network total input power by the input power of all charge controllers we are listening to and account their battery output power instead. the remainder of the network input power, i.e., the input power of all networked charge controllers that we are not listening to, is corrected for the average efficiency and added to the return value.
Status: Not tested yet. Can't test tomorrow, this needs to wait until Sunday.
Closes #1793.

Fix: prioritize VE.Direct network power

---

webapp/src/components/InputElement.vue
webapp/src/types/DtuConfig.ts
webapp/src/views/DtuAdminView.vue

Closes #1640
change `serial` to type `string` and add converting wrapper around it.

Fix: DTU serial change not possible

---

src/powermeter/udp/victron/Provider.cpp

Fix: skip unexpected Modbus UDP answers from Victron power meter

---

include/PowerLimiter.h
src/MqttHandlePowerLimiter.cpp
src/PowerLimiter.cpp

Closes #1914.
There is a second commit in this PR which has barely anything to do with #1914, but became quite obvious to me when looking at the code to understand said issue.

Fix: DPL: full solar-passthrough state

---

include/battery/zendure/Constants.h
include/battery/zendure/Provider.h
include/battery/zendure/Stats.h
src/battery/zendure/Provider.cpp
src/battery/zendure/Stats.cpp

Various fixes for AIO 2400
Fixes #1907 
Tasks:

[Zendure] Fixes for AIO 2400

---

webapp/src/views/BatteryAdminView.vue
webapp/src/views/GridChargerAdminView.vue
webapp/src/views/PowerLimiterAdminView.vue
webapp/src/views/PowerMeterAdminView.vue
webapp/src/views/SolarChargerAdminView.vue

this sets the auto-dismiss value for success messages on OnBattery-specific admin views.

webapp: auto-dismiss success messages

---

include/battery/zendure/Stats.h

Added AB2000X S/N to detection

Zendure: Add support for AB2000X
