include/PylontechCanReceiver.h
platformio.ini
src/PylontechCanReceiver.cpp

Hi,
I tried to get my Pylontech Battery to speak to the ESP today but was not successful.
The can library (CAN.h) that is used for this link has a number of pending pull requests that seem to be related to newer ESPs. I tried to use the lib with a different device in the past and had similar issues.
I switched to twai.h which is more up to date. Also expressif claims that there are some HW related fixes implemented in this lib. I was able to read the Pylontech battery values with this change.
@berni2288 I understand that you have committed this feature originally. Can you check and comment?
Also I replaced the Messages printout.
Thanks,
Malte

swap CAN bus library to better support newer ESPs

---

src/Huawei_can.cpp

This is a leftover from the discussion around the SPI interface change here:
https://github.com/helgeerbe/OpenDTU-OnBattery/pull/144
Back then I submitted a PR to change the SPI interface in openDTU that got rejected (for reasons that made sense) but I forgot to make the change to the Huawei related code.
The conflict is in https://github.com/helgeerbe/OpenDTU-OnBattery/blob/master/src/InverterSettings.cpp which also uses the VSPI interface (line 26)

Changing Huawei SPI interface

---

README.md
include/MqttHandlePowerLimiter.h
include/PowerLimiter.h
src/MqttHandlePowerLimiter.cpp
src/PowerLimiter.cpp
src/WebApi_powerlimiter.cpp
src/main.cpp

This adds basic MQTT control of the power limiter. 
The change is larger as I reworked the state machine code and the calc/set functions (there is a separate PR pending in https://github.com/helgeerbe/OpenDTU-OnBattery/pull/164)
Rationale for refactoring the existing code was:
- issues with stopping / start the inverter
- the code depth and code complexity 
Based on my understanding all the old functionality should be enabled, but please let me know if I missed to cover a case.
My original plan was to provide these changes piece wise so that the amount of changes is not overwhelming but I'm currently not clear if an approach with 
- smaller individual changes 
- one large change
- or no refactoring 
is actually preferred.

Enable / Disable power limiter via MQTT

---

.github/workflows/build.yml

This patch changes the output filenames of the github actions.
Tested on my fork, works good.
Additionally, to receive the binary files with the correct content, this project has to create its own tags which will result in releases with the correct content. Maybe its also necessary to delete the tags coming from upstream tbnobody/OpenDTU

Fix: github build create opendtu-onbattery.* files

---

include/PowerLimiter.h
src/PowerLimiter.cpp

@helgeerbe mentioned here: https://github.com/helgeerbe/OpenDTU-OnBattery/pull/172#issuecomment-1523468992 that I broke the sun indicator for Power Limiter solar pass-through. I investigated and believe the code in this PR fixes this. It works for me but I hardly ever get direct SolarPassthrough in my setup. 
Can you kindly check?
Note: I did not compare the MPPT power and the inverter power to indicate if the battery is actually being discharged or charged. Is that the desired behavior or shall this be done?
Note 2: The UI shows the last requested inverter power currently. This is correct as per methods used currently but also means that there is a power value shown case if the inverter is off. Should this indicate 0 in this case?

Bring back the sun indicator

---

include/PowerLimiter.h
src/PowerLimiter.cpp

there is no need to assume and hardcode a fixed efficiency for the Victron solar charger. the charger reports the voltage and current at its battery terminal, which can be used to calculate the charger's actual power output.
the fallback to 100% for the efficiency of the Hoymiles inverter, in case it is not producing power, is too optimistic. this commit proposes to use 96.7% as the efficiency for that case, which is the peak efficiency for many (all?) Hoymiles inverters as per datasheet. that value should be closer to the real efficiency that will be achieved once the inverter is turned on.

DPL: fix efficiency calculation

---

src/PowerLimiter.cpp

in case the communication to the Victron charger is disrupted, the respective values in `VeDirect.veFrame` are not invalidated such that we would notice a problem. instead, `isDataValid()` should be used to make sure that the Victron charger is actually alive and that we can trust to use the reported values.

DPL: use vedirect isdatavalid

---

src/PowerLimiter.cpp

the requested `newPowerLimit` was indeed limited to the configured maximum inverter output and the result was stored in `effPowerLimit`. later, however, `effPowerLimit` must be scaled up (if necessary), not `newPowerLimit`. the latter variable is not respecting the configured maximum inverter output.
Closes #284.

DPL: fix the configured upper limit not being respected

---

include/PowerLimiter.h
lib/Hoymiles/src/inverters/HM_Abstract.cpp
src/PowerLimiter.cpp
src/WebApi_ws_vedirect_live.cpp

This change focuses on two features: (1) The DPL loop is calculating a new power limit much more often, while not calculating anything while it is unreasonable to do so. (2) A DPL status is introduced, which shall make it more transparent to understand what the DPL is currently doing. The status is useful to be displayed on the web application in the future and is complementary to `getPowerLimiterState()`.
More conditions are checked before calculating a new power limit than before, e.g., `getEnableCommand()`, while the conditions that are checked should be much easiert to understand. Waiting for all radios to be idle was a very conservative condition, which is replaced by waiting for an empty command queue for the specific inverter. To implement this, a change is included that is also …

DPL: add status, improve responsiveness

---

include/Configuration.h
lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
lib/VeDirectFrameHandler/VeDirectFrameHandler.h
src/Configuration.cpp
src/WebApi_vedirect.cpp
src/main.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json
webapp/src/router/index.ts
webapp/src/types/VedirectConfig.ts
webapp/src/views/VedirectAdminView.vue
webapp/src/views/VedirectInfoView.vue

* the polling interval was meant to limit the amount of MQTT updates. however, that is already controlled by the global MQTT publish interval. the removed interval was instead used to limit polling of the VE.Direct UART for incoming data.
the Victron device sends data unsolicited. the VeDirectFrameHandler does not implement any polling mechanism. no data is ever sent to the Victron device.
what the removed polling interval did was cause a buffer overrun of the HardwareSerial class, since the incoming data was not processed in time. so every five seconds, we read a whole valid VE.Direct frame, plus some old data, which was not a whole frame, leading to VE.Direct error messages to pop up.
with the polling interval removed, no framing errors are reported, and instead we gain new data from …

Fix vedirect polling

---

include/PowerLimiter.h
src/PowerLimiter.cpp

* wait for valid time information (as we know the Hoymiles library will do nothing until valid time information is available).
* wait for device info to be ready. otherwise we continuously calculcate the new power limit to be zero, until the `maxPower` info is available.
* fix the calculation backoff initialization: when initializing to zero, doubling will still make it zero, leading to useless high frequency power limit calculations after startup (until the inverter is ready and an actual non-zero power limit was calculated for the *second* time).

DPL: check more requirements and fix backoff initialization

---

include/MqttHandleVedirect.h
src/MqttHandleVedirect.cpp
src/WebApi_mqtt.cpp

In Home Assistant, when Home Assistant MQTT-Auto-Discovery is active, almost all Sensors of the auto-discovered Victron device in Home Assistant become "unavailable" after a short time - except those Sensors with frequent changes like battery voltage or panel voltage.
This patch introduces regular mqtt updates for all VE.Direct sensors when MQTT-Auto-Discovery is enabled.

fix: Home Assistant MQTT-Auto-Discovery with VE.Direct

---

src/PowerLimiter.cpp

Smaller PR that:
1. Disables debug printouts
2. Increases the threshold for producing channel detection.
3. Fixes an issue with maximum power limiting
Rationale:
1. The PL was recently changed to no longer run in a 10s interval. This causes the debug printouts to be printed way more often. I believe this has lead to stability issues highlighted here https://github.com/helgeerbe/OpenDTU-OnBattery/issues/298 
This PR disables the printouts for now which is kind of a hotfix
2. My Inverter reports a power of 0.9W on a single channel when idle. The other channels indicate about 1.5W. This triggers the producing channels detection code and will scale a requested limit by a factor of 1.3 when starting up. This PR increases the detection threshold to 2W.
3. When no active channels are detected …

Disable PL debug mode, increasing power threshold for active channel

---

include/PowerLimiter.h
src/PowerLimiter.cpp

if the new calculated power limit is below the minimum power limit setting, the inverter is shut down. the shutdown() function is called every time this condition is detected, which is also true if the inverter is kept shut down for longer. that happens while the battery is charging in particular (solar passthrough off). there are other cases.
in such cases we still want to get into the DPL status "stable". to be able to determine this stable state, we must know if the call to shutdown did actually initiate a shutdown or if the inverter is already shut down.
we then can forward this "changed" or "not changed" info up the call chain, where the loop() will know that the system is actually stable.
see discussion with @peff74 in #309

DPL: increase backoff while inverter is kept shut down

---

include/MqttHandlePylontechHass.h
src/MqttHandlePylontechHass.cpp
src/main.cpp

When OpenDTU has a Pylontech CAN Bus Battery connected and enabled, this patch adds the discovery routine for Home Assistant
Closes #278

Feature: add Home Assistant MQTT discovery for Pylontech battery

---

webapp/index.html
webapp/src/components/NavBar.vue

adjust window-title and live-view header from OpenDTU to OpenDTU-onBattery 
Additionally change orientation of battery symbol to vertically centered (looks nicer)
Needs rebuild of Webapp!

Fix: WebApp Live-View: adjust window-title and header

---

README.md
docs/MQTT_Topics.md
src/MqttHandleHuawei.cpp

I have added the possibility to set the offline parameters for the Huawei power supply over MQTT.
The offline parameters are used if the power supply does not have a CAN connection at startup.

Feature: set Huawei offline parameters via MQTT

---

README.md
docs/MQTT_Topics.md
src/PylontechCanReceiver.cpp

I added the data age for the MQTT Battery Topic and adjusted the doc.

Add data age at battery MQTT

---

src/PowerLimiter.cpp

This fix addresses an issue that I discovered after setting up the system with slightly changed voltage values. 
In cases where the values from the Pylontech battery are recent but the respective %tage threshold has not been reached, code meant for voltage based evaluation was executed. This caused unexpected behavior as the voltage based threshold was reached sooner then the %tage based threshold
I'm still testing so I leave this as draft for now but it is pretty obvious in my mind

SoC based threshold detection fix

---

include/PowerMeter.h
src/PowerMeter.cpp

When subscribing to a topic whose payload cannot be parsed as a float value, an exception would be triggered in the PowerMeter implementation. The code in this PR catches the exception and handles it gracefully:
```
Received MQTT message on topic: solar-staging/dtu/status
PowerMeterClass: cannot parse payload of topic 'solar-staging/dtu/status' as float: online
```
Make sure that the timestamp `_lastPowerMeterUpdate` is only updated by the MQTT callback if a topic was processed that actually matches one of the subscribed topics.
Upon changing the MQTT settings and submitting the new settings through the web application, PowerMeter::init() is called. That probably makes sense so it can be ensured that the topics are subscribed to using a possible new broker. However, the old subscriptions …

PowerMeter fixes

---

src/WebApi_mqtt.cpp
webapp/src/locales/en.json
webapp/src/types/MqttStatus.ts
webapp/src/views/MqttInfoView.vue

* Fix a typo that prevented the user from enabling verbose logging at all.
* Add the verbose logging setting to the webapp status page.
Will also be added to the upstream MR https://github.com/tbnobody/OpenDTU/pull/1165.

MQTT verbose logging fixes

---

include/MqttSettings.h
src/MqttSettings.cpp
src/main.cpp

processing a published valued on a subscribed topic is currently running in a task that is not the task executing the main loop(). that's because the espMqttClient(Secure) was constructed without arguments, which selects the constructor with two arguments priority and core, both of which have default values. that constructor selects espMqttClientTypes::UseInternalTask::YES, causing a task to be created in which context the MQTT client loop is executed.
MQTT subscribers assume they are running in the same context as the main loop(). most code assumes exactly that. as the scheduler is preemptive and very little (none at all?) code is interlocked, we have to make sure to meet the programmer's expectations.
this changeset calls the MQTT client loop in the context of the main loop() and …

execute MQTT client synchronously in main loop()

---

include/PowerLimiter.h
src/PowerLimiter.cpp

This PR mangles two changes. The commits are separated. They do, however, build on one another.
1. "Improve" the DPL verbose logging. Please see the commit message for a list of changes. Some are purely cosmetic, some are arguably improvements.
2. Inhibit solar passthrough if the battery SoC or voltage is below the respective stop threshold.
Reasons for 2:
* If solar passthrough is active for a couple of hours or days and the battery is slightly discharged the whole time because the inverter is using a little too much power, maybe because the losses are bigger than anticipated, then this becomes a problem.
* The battery self-discharges over time, which might become an issue on prolonged periods with little sunshine.
* The inverter uses power at night. Very little, but this inevitable …

Inhibit solar passthrough while battery below stop threshold

---

webapp/src/views/HomeView.vue

```
instead of hiding views, we can also avoid adding them to
the DOM. this has a couple of advantages:
* no HTTP request for data is sent and no websocket connection
is established for disabled features.
* JavaScript that causes errors due to incomplete or incompatible
data of features that are disabled anyways do not trigger the
browser debugger.
```
I am working on changes to the Battery live view to accommodate the JK BMS values (and making it very generic for future battery interfaces) and I am stumbling on a couple of annoying problems. This is one of them.

live view: remove disabled -OnBattery-specifc views from DOM

---

include/WebApi_ws_vedirect_live.h
src/WebApi_ws_vedirect_live.cpp

```
the size allocated for the HTTP request response was too little,
while the size for the buffer of the websocket output was increased already.
add a new member variable and use it in both context, such that
increasing the buffer size to accomodate more space (for the JSON
data in particular) will benefit both contexts in the future.
```
I am working on changes to the Battery live view to accommodate the JK BMS values (and making it very generic for future battery interfaces) and I am stumbling on a couple of annoying problems. This is one of them.
All of the web API implementations should be checked for different buffer sizes, like the one fixed here. Or even better, the same member variable should be introduced to all of them to avoid this kind of problem in the future. If anybody …

VE.Direct: websocket and status API response size

---

include/MqttHandlePowerLimiter.h
include/PowerLimiter.h
src/MqttHandlePowerLimiter.cpp
src/PowerLimiter.cpp
src/WebApi_powerlimiter.cpp

getMode() returned a bool. probably its return type was not adjusted when the third mode was introduced. this lead to mode 2 being cast to true implicitly, which in turn was used to construct a String, such that "1" was published as the DPL mode when in fact it was 2.
make the mode an enum class to avoid such problems in the future.
inline getMode() and setMode().
fix indention.
more changes that I found would improve the code quality while looking to fix the actual issue:
* there is no need to tokenize and check the topic of a received MQTT message if we only subscribe to a single topic. all messages will be for that topic. avoid testing the topic in the callback alltogether.
* use std::string and std::stoi over allocating and deleting a buffer and copying charactes around.
* use a …

Fix DPL Mode 2 MQTT Status

---

webapp/vite.config.ts

`/vedirectlivedata` originally was also proxied in the version of the vite config in this project, but that was wiped with the recent merge of the upstream master branch.
This change re-adds `/vedirectlivedata` to be proxied and adds `/batterlivedata` to be proxied as well, which is also specific to this project and not part of the upstream project.

vite config: also proxy vedirect- and batterylivedata

---

include/MessageOutput.h
src/MessageOutput.cpp

I am trying to convince tbnobody that my changes proposed in https://github.com/tbnobody/OpenDTU/pull/1212 are valuable and do not have a detrimental effect on the project. However, the pull request sits idle.
In the meantime, I am still concerned that the web console message can only be trusted to some extent, as they can still be interleaved in between tasks, and because messages are simply dropped if any component tries to print "too much" messages until the next time MessageOutput's `loop()` is called.
For that reason, I would like to propose these changes to this project.
I have these changes deployed on my production unit and have no issues whatsoever. Additionally, I sneaked the changes into pre-releases of my fork, and I heard nothing about any issues.

Messages: thread-safety and dynamic memory

---

lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
lib/VeDirectFrameHandler/VeDirectFrameHandler.h

* remove unused `#defines`
* remove unused member variable
* fix indentation and trailing whitespace
Waiting for #416 as this is based on those changes. I will rebase this after #416 is merged and then mark it ready.

Vedirect Cleanups

---

src/HttpPowerMeter.cpp

This PR fixes the kernel panic issue outlined and discussed here: https://github.com/helgeerbe/OpenDTU-OnBattery/issues/381
The uptime of my system previously hardly ever reached 8h. This code has been running without reboots for 5 days now. 
In addition a smaller change how errors are handled was done to HttpPowerMeterClass::updateValues(). In case of an http request or parse errors subsequent requests/parses are cancelled
Thanks @schlimmchen for the support

HTTP Power Meter kernel panic fix

---

lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp

this avoids the debug buffer being overrun if verbose logging is disabled in particular. that would happen because the buffer would only be reset if verbose logging was enabled but filled in any case.

VE.Direct: do not use debug buffer at all if verbose logging disabled

---

include/BatteryStats.h
include/JkBmsDataPoints.h
src/BatteryStats.cpp
src/JkBmsController.cpp
src/JkBmsDataPoints.cpp

This changeset implements publishing all JK BMS data points (with two exceptions) to the MQTT broker.

JK BMS: Support for MQTT

---

src/PinMapping.cpp
src/VictronSmartShunt.cpp

This PR removes the necessity for defining a GPIO Pin for tx for Victron devices. Currently sending commands is not done and thus only the rx pin is used for MPPT and SmartShunt devices.
I thought about removing the victron_tx part completely in the code, but I think it will make potential future support for sending commands to the victron devices easier, but the tx pin should not be mandatory at the moment.
I think, this would eliminate a lot of confusion, what do you think?

Allow for defining only rx pin for VE.direct

---

include/Huawei_can.h
src/Huawei_can.cpp

Multiple issues have been raised related to Huawei AC charger connection issues (links below). These are related to the response of the Huawei PSU that delivers the individual values (actual current, voltage etc.) as separate CAN bus messages. These were previously read as part of the main() thread which used to work okisch. The changes implemented over the course of the summer however caused this code to be executed less often. This now causes frequent overrides of the small CAN receiver buffer by newer messages resulting in data loss.
This PR implements CAN communication as a separate thread, responsible for CAN bus reads and writes. This thread fetches data more often but is limited to CAN bus communication for performance reasons only. My thought was to keep the methods of the CAN bus …

Move Huawei CAN bus communication to separate thread

---

include/PowerLimiter.h
src/PowerLimiter.cpp

avoid staleness in case the same power limit is calculated over and over again, hence no new power limit value is calculated and hence no power limit command is sent to the inverter. staleness occurs in this case if the first power limit command to establish the respective limit was not received by the inverter. one can easily simulate a situation where the same power limit is caluclated over and over again: with a battery above the start threshold, set a very low upper power limit for the inverter (DPL setting). that value will be used as the limit as long as the power meter reading is larger than that.
we could also check the limit reported by the inverter. however, that value is in percent of the inverter's max AC output, and is often not the same value as we requested as the limit, …

DPL: (re-)send power limits periodically

---

src/PowerMeter.cpp

as soon as a read operation from an SML device was successful, the power meter timestamp must be updated.
return early (in any case) if the power meter is not enabled, simplifying if-statements.
closes #498.

Fix: PowerMeter: update _lastPowerMeterUpdate for SOURCE_SML

---

include/BatteryStats.h
lib/VeDirectFrameHandler/VeDirectShuntController.cpp
lib/VeDirectFrameHandler/VeDirectShuntController.h
src/BatteryStats.cpp

If have bought and attached a battery temperature sensor to my SmartShunt. When the sensor is correctly set up via the Victron App, the SmartShunt also periodically sends temperature data. This PR adds the temperature to the web interface, when temperature data is available.

Add temperature sensor data to Victron SmartShunt

---

include/VictronMppt.h
src/VictronMppt.cpp
src/WebApi_ws_live.cpp

The refactor in #505 was not tested with VE.Direct turned off. Sorry for that.
If VE.Direct is turned off, the web API implementation still adds totals of the MPPT to be displayed by the web app on the top. It used `VictronMppt.getData()`, which did print an error message on the console, but did not return the proper fallback data structure. It returned a `std::shared_ptr` pointing to `nullptr` rather than one pointing to a default-initialized MPPT data struct, which was my intention.
The fix is simple, see the first commit. However, the error message is still printed on the console, since the web API implementation adds the totals unconditionally. Adding them only if VE.Direct is enabled is not working out, since those values are defined to be part of the respective typescript type …

Fix: VE.Direct refactor issues from #505

---

webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json

Replace all links pointing to the upstream project with links pointing to this project -- where applicable.
Closes #499.

Fix: replace links to upstream project where applicable

---

src/MqttHandlVedirectHass.cpp

efficiency does not exist so NULL should be the correct value.

Fix HASS sensor unit autodiscovery

---

src/WebApi_Huawei.cpp
src/WebApi_ws_Huawei.cpp
webapp/src/components/HuaweiView.vue

This aims to fix #487. It has however to be tested by someone having a Huawei charger as I do not have one.
In essence: Internally the efficiency is stored as a float value between 0 and 1. For the webinterface it has to be converted to % and thus the value has to be multiplied by 100.

Fix Display Bug for Huawei AC Charger in web interface

---

include/Huawei_can.h
src/Huawei_can.cpp

The Huawei PSU currently allows setting current / voltage values externally when running in internal power control mode. This leads e.g. to current limits received via MQTT being applied for a brief time until they're being changed again by the power control in HuaweiCanClass. In my specific case I started to control the operation mode externally which resulted in frequent on/off switches.
This PR makes the original setValue method private (renamed to _setValue) and adds a new public setValue method that includes a check / rejects changes in this case.

Huawei AC charger: prevent setting current limit when internal power control mode is enabled

---

src/Battery.cpp

the updateSettings method is called from the web server's context and therefore accesses _upProvider in a different context than the TaskScheduler. the lock_guard needs to protect _upProvider.

Fix: move battery's lock_guard to updateSettings()

---

include/MessageOutput.h
src/MessageOutput.cpp

this commit re-introduces the changes from #418, which were effectively reverted with d49481097 (merge commit introducing TaskScheduler).
these adjustments are important to guarantee unmangled log messages and more importantly, to guarantee that all messages from a particular component are printed to the web console, which most people use to copy messages from when reporting issues.
* use dynamic memory to allow handling of arbitrary message lenghts.
* keep a message buffer for every task so no task ever mangles the message of another task.
* every complete line is written to the serial console and moved to a line buffer for sending them through the websocket.
* the websocket is always fed complete lines.
* make sure to feed only as many lines as possible to the websocket handler, so that …

Fix: thread-safety and dynamic memory for MessageOutput

---

webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json
webapp/src/views/AcChargerAdminView.vue
webapp/src/views/BatteryAdminView.vue
webapp/src/views/PowerLimiterAdminView.vue
webapp/src/views/PowerMeterAdminView.vue
webapp/src/views/VedirectAdminView.vue

the upstream project introduced a new Vue component "FormFooter", which is used to end an input form, namely all settings forms. we should not only use this component as well, but the save button on our forms actually broke since the text dtuadmin.Save is replaced by base.Save.
also replace the use of dtuadmin.Seconds with base.Seconds, such that an upstream change to dtuadmin.Seconds will not break the battery admin an AC charger views.
closes #568.

Fix: use FormFooter in OnBattery-specific forms

---

include/MqttHandleHuawei.h
src/MqttHandleHuawei.cpp

MQTT message callbacks are executed in the MQTT thread context. when processing topics that control the huawei AC charger, we must avoid executing methods that are not thread-safe. this change bound the methods to be called to the respective parameters and executes them in the TaskScheduler context, such that they no longer need to be thread-safe.
I tested this change by publishing values to the respective topics and generating a log message in the respective HuaweiClass method. Hence I am highly confident that this change does only what it is intended to do: make sure that the functions are executed in the TaskScheduler context, i.e., within the `MqttHandleHuaweiClass::loop()` method.

Fix: switch context when handling AC charger MQTT messages

---

include/MqttHandlePowerLimiter.h
src/MqttHandlePowerLimiter.cpp

MQTT message callbacks are executed in the MQTT thread context. when processing topics that control the DPL, we must avoid executing methods that are not thread-safe. this change binds the methods to be called to the respective parameters and executes them in the TaskScheduler context, such that they no longer need to be thread-safe.

Fix: switch context when processing DPL MQTT requests

---

src/WebApi_prometheus.cpp
src/WebApi_sysstatus.cpp
webapp/src/components/HeapDetails.vue
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json
webapp/src/types/SystemStatus.ts
webapp/src/views/SystemInfoView.vue

this change adds the values of ESP.gteMaxAllocHeap() and ESP.getMinFreeHead() to the prometheus metrics and the system information object. the web UI uses these values to diplay the size of the largest free contiguous block, calculate a rough estimate for the level of fragmentation, and the maximum usage of heap memory since boot in absolute and relative amounts.
the last card in this screenshot is new:
now let's observe if memory fragmentation is indeed an issue in this project.
notice that we will still miss the case where two processes (not TaskScheduler tasks) are both trying to allocate more than 50% of the largest free block.

Feature: add heap details to system info and prometheus

---

include/VictronSmartShunt.h
src/VictronSmartShunt.cpp

currently the whole SmartShunt data structure is copied to the BatteryStats instance in every loop, even though the data cannot possibly have changed. this is quite an expensive task to do in every loop. this change tracks the last update timestamp and only does the copy operation if an actual updated data structure was received from the smart shunt.

avoid too frequent SmartShunt data copies

---

src/Display_Graphic.cpp
src/WebApi_device.cpp
src/main.cpp

if the power meter is enabled, the display will use two of three out of every three-second time slot to show the grid consumption.
closes #620.
This was fun and I like the result, but it took way too much time. Fiddling with the display is much more time consuming as one might think. At least it was in this instance for me.
The display shows this screen for three seconds:
This one for another three seconds (last line changes ever three seconds):
The third out of three three-second time slots will still show the total yield (if this was the actual successor screen of the frame above, it would show the date and time in the last line...):
Works for French as well (the word "reseau" is quite long):
I made sure that it works for small display as well:
Changes were made to the calculation of …

Feature: show power grid usage on display

---

.github/workflows/build.yml

This change makes the build runner switch to a meaningful branch name, which will then appear as the "Firmware Branch" in the System Info of the web application. This helps users testing pull-request builds identify that they are actually using the changes from the respective pull request.
Tested successfully on my own fork, see https://github.com/schlimmchen/OpenDTU-OnBattery/actions/runs/8133322818?pr=11

pull requests: use a meaningful branch when building

---

include/BatteryStats.h
include/WebApi_ws_live.h
src/BatteryStats.cpp
src/WebApi_ws_live.cpp
webapp/src/views/HomeView.vue

the update frequency of Victron MPPT charger data, the battery SoC, the huawei charger power, and the power meter differ from one another, and differ in particular from the inverter update frequency.
the OnBattery-specific data is now handled in a new method, outside the upstream code, which merely calls the new function(s). the new function will update the websocket independently from inverter updates. also, it adds the respective data if it actually changed since it was last updated through the websocket.
for the webapp to be able to recover in case of errors, all values are also written to the websocket with a fixed interval of 10 seconds.
in particular, this allows to observe power meter readings update while the inverters are being fetched. for me this makes a big difference as the …

Decoupled live view intervals

---

src/PowerLimiter.cpp

do not scale limit if inverter is not producing, as DC channel power is expected to be close to zero anyways.
do not scale limit if current inverter limit is small, such that channels might produce very little power exactly because the limit is so low.
move the calculation out of setNewPowerLimit and into a new function, so that we can make use of return statements there.

fix: DPL: limit scaling sanity checks

---

include/MqttHandlePowerLimiter.h
include/MqttHandlePowerLimiterHass.h
src/MqttHandlePowerLimiter.cpp
src/MqttHandlePowerLimiterHass.cpp
src/WebApi_battery.cpp
src/WebApi_powerlimiter.cpp
src/WebApi_vedirect.cpp
src/main.cpp

This pull request adds MQTT topics to set the thresholds of the dynamic power limiter via MQTT.
Closes #677

Set powerlimiter thresholds via MQTT

---

src/BatteryStats.cpp

Um Dezimalstellen für die charged und discharged Werte vom SmartShunt mit anzuzeigen, müssen die Datentypen angepasst werden, ich war mal so frei und habe das eben gemacht.

Fix SmartShunt energy values

---

include/PowerMeter.h
src/PowerMeter.cpp

the SDM power meter (among others) writes the power consumption of three phases in multiple steps. this change helps to prevent getTotalPower() reading intermediate values, i.e., reading a new value for phase 1 but old values for phase 2 and 3 since phase 2 is currently read.
cache the values, and write them all at once, protected by a mutex, later.
closes #732.

fix: prevent getTotalPower() reading intermediate results

---

include/BatteryStats.h
src/BatteryStats.cpp
src/MqttHandleBatteryHass.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json

Da bisher keine "eigenen" Victron SmartShunt Werte nach HA per Autodiscovery verfügbar gemacht werden habe ich dort nun ein paar Werte veröffentlicht. 
Desweiteren habe ich zum LiveView die Aktuelle Leistung, Verbrauchten Amperestunden und die Letzte volle Ladung hinzugefügt.
Man könnte sich nun überlegen das noch in Kategorien sinnvoll zu unterteilen, aber fürs erste war das für mich so in Ordnung. 
Bei der Benahmung bin ich noch für eventuell bessere Vorschläge offen :D

add new Victron SmartShunt values to liveView and MQTT (HASS)

---

include/PinMapping.h
include/PowerMeter.h
src/PinMapping.cpp
src/PowerMeter.cpp
src/WebApi_powermeter.cpp

in your pin_mapping.json, add a powermeter object like this:
```
[
{
"name": "My Board",
...
"powermeter": {
"rx": <num>,
"tx": <num>,
"dere": <num>
},
...
}
]
```
the SML power meter requires the rx pin to be set. the SDM power meter requires the rx and tx pins are set. the "dere" pin pin is optional and if set, this pin controls the driver enable and receiver enable pins of the RS485 transceiver. the SDM library handles this pin.
closes #771.

Feature: implement PowerMeter pin config for serial interfaces

---

include/BatteryStats.h
include/Configuration.h
include/Huawei_can.h
src/Configuration.cpp
src/Huawei_can.cpp
src/WebApi_Huawei.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json
webapp/src/types/AcChargerConfig.ts
webapp/src/views/AcChargerAdminView.vue

This PR connects the Huawei AC-Charger with the Battery BMS. It specifically introduces the following features:
When the BMS issues an charge immediate request and the charger is in internal automatic control mode then charging is started with full configured power. This behavior enabled / disabled on the GUI
The Huawei charger will respect BMS current limits now when charging and limit the current taking the BMS limit and an estimate of other DC sources into account.
I did some testing but would like to monitor this a bit over the course of the coming days. Marking this PR as draft for now.
The request is in https://github.com/helgeerbe/OpenDTU-OnBattery/issues/723

Huawei AC-Charger (Pylontech) BMS connection 

---

include/BatteryStats.h
include/MqttHandleVedirect.h
include/MqttHandleVedirectHass.h
include/VictronMppt.h
include/WebApi_ws_vedirect_live.h
lib/VeDirectFrameHandler/VeDirectData.cpp
lib/VeDirectFrameHandler/VeDirectData.h
lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
lib/VeDirectFrameHandler/VeDirectFrameHandler.h
lib/VeDirectFrameHandler/VeDirectMpptController.cpp
lib/VeDirectFrameHandler/VeDirectMpptController.h
lib/VeDirectFrameHandler/VeDirectShuntController.cpp
lib/VeDirectFrameHandler/VeDirectShuntController.h
src/BatteryStats.cpp
src/MqttHandlVedirectHass.cpp
src/MqttHandleVedirect.cpp
src/VictronMppt.cpp
src/VictronSmartShunt.cpp
src/WebApi_ws_vedirect_live.cpp

* add unique prefix to VE.Direct messages. this makes it easier to map debug messages to one-another.
* properly handle fragmented VE.Direct messages. queue every text event until the frame was checked by it checksum. then process the data directly into the buffer struct. do not clear the buffer struct, so it will always include the most recent value of a particular data point.
* use float rather than double. double precision floating point numbers are not needed to handle VE.Direct values. handling double is implemented in software and hence *much* more resource intensive.
* make state machine timeout robust against overflow.
Closes #774 and #689.

Properly handle VE.Direct fragmentation

---

lib/VeDirectFrameHandler/VeDirectData.cpp
lib/VeDirectFrameHandler/VeDirectData.h
lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
lib/VeDirectFrameHandler/VeDirectFrameHandler.h
lib/VeDirectFrameHandler/VeDirectFrameHexHandler.cpp
lib/VeDirectFrameHandler/VeDirectMpptController.cpp
lib/VeDirectFrameHandler/VeDirectShuntController.cpp
src/BatteryStats.cpp
src/MqttHandlVedirectHass.cpp
src/MqttHandleVedirect.cpp
src/VictronMppt.cpp
src/WebApi_ws_vedirect_live.cpp

- VeDirect: add of text message values "IL", "AR" and "MON"  Fix issue #834 
- VeDirect: discard BMV and Async MPPT History Data

Minor VeDirect Improvements (parse additional values, ... )

---

src/WebApi_ws_vedirect_live.cpp

The precision of Victron's yield displayed on the WebView is too high. For my Victron MPPT 100/20, it shows only a 10 Wh precision. I believe this precision is not dependent on the MPPT being used. 
So now only 2 decimals are shown.

Fix Victron yield precision

---

src/WebApi_ws_live.cpp

makes the value match its description. since most values in the top part of the live view are related to the AC side of the system, it makes sense to use the correct value rather than to change the description.
closes #846.

Fix AC charger power in live view

---

include/PowerLimiter.h
src/PowerLimiter.cpp

avoid performing a calculation based on a (slightly) outdated power meter reading, which was aquired just before the limit was actually applied by the inverter, but which was received by OpenDTU-OnBattery after the inverter stats.
closes #868.

DPL: insist on power meter value more recent than inverter stats

---

include/Configuration.h
include/HttpPowerMeter.h
include/WebApi_powermeter.h
src/Configuration.cpp
src/HttpPowerMeter.cpp
src/WebApi_powermeter.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/types/PowerMeterConfig.ts
webapp/src/views/PowerMeterAdminView.vue

This changeset allows to
* select the unit of a value retrieved using the HTTP(S)+JSON power meter implementation. Supported units are mW (milli Watt), W (Watt, the default) and kW (kilo Watt).
* instruct to change the retrieved value's sign such that it is positive when it means to indicate power consumption.
Closes #451 and #735 and #882.

Feature: HTTP power meter: mW/kW as unit and sign inversion

---

include/PowerLimiter.h
src/MqttHandlePowerLimiter.cpp
src/PowerLimiter.cpp

we found that the inverter sometimes stops responding to commands, especially to the "start producing" command. we now count the number of consecutive timeouts when trying to send a new limit or power state commands. after two timeouts were recorded, every additional timeout will send a restart command to the inverter.
as a last resort, if the counter keeps climbing, the DTU is restarted.
notice that this only targets unresponsive inverters which are reachable. unreachable inverters are not restarted and do not cause a DTU reboot. this is important for solar-driven inverters, which are unreachable during the night. the DPL will not calculate a new limit and hence the updateInverter() method will do nothing while the target inverter is unreachable.
publish the timeout counter to MQTT for …

Feature: restart unresponsive inverter

---

src/PinMapping.cpp

Victron pins RX2 and TX2 are incorrectly initialized. Proposed fix for issue described here:
https://github.com/helgeerbe/OpenDTU-OnBattery/issues/916

Victron pin define fix

---

include/JkBmsController.h
include/VictronSmartShunt.h
lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
lib/VeDirectFrameHandler/VeDirectShuntController.cpp
src/JkBmsController.cpp

this allows to use two VE.Direct interfaces, as there is no conflict regarding HW serial port 2 after making the battery interfaces use serial port 0 on devices with USB CDC. on those chips HW serial 0 is free to be used since serial messages are written through the USB interface directly.

battery interface: use HW serial 0 on ESP32-C3 or S3

---

.github/workflows/build.yml

this is an attempt to exempt the whole build workflow (and respective releases from being created) for upstream tags.
inspired by https://github.com/orgs/community/discussions/25615.

workflow: ignore v** tags

---

include/HttpPowerMeter.h
platformio.ini
src/HttpPowerMeter.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/views/PowerMeterAdminView.vue

The firmware for environments `generic` and `generic_esp32` (and probably more) finally became to large, see #950.
This changeset removes the FirebaseJson and the rweather/Crypto libs from the build and implements the functionality they provided using existing libs. This saves nearly 20kB of flash memory. The firmware now works again on non-S3 ESP32.
Closes #950.

Remove redundant libraries (FirebaseJson and Crypto)

---

src/Configuration.cpp

Due to a couple of typos values of `solar_passtrough_enabled` and `solar_passtrough_losses` were lost after a restart.

Bugfix: solar_passthrough_losses lost after restart

---

src/HttpPowerMeter.cpp

this implements accessing array members in an ArduinoJSON object following the FirebaseJson syntax. the FirebaseJson lib was previously removed to save flash memory, and logic was implemented to find a JSON node using the FirebaseJson path syntax, restoring the functionality. however, array access was not implemented.
this change also addresses leading and trailing and double forward slashes in the path expression.
moreover, much more expressive error messages are now generated in case the path could not be resolved.
Closes #966.

Fix: restore JSON array access for HTTP power meter

---

include/BatteryStats.h
lib/VeDirectFrameHandler/VeDirectData.h
lib/VeDirectFrameHandler/VeDirectShuntController.cpp
src/BatteryStats.cpp
src/MqttHandleBatteryHass.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json

I'm excited to share my first pull request, which focuses on enriching the MQTT data for batteries in a serial configuration. This enhancement includes not only additional data fields but also improves the decimal accuracy for both live view displayed data and MQTT transmissions.
**New Data Fields for HomeAssistant MQTT Auto Discovery:**
1. Midpoint Voltage:
- Added midpoint voltage information to provide a more comprehensive view of the battery's state in a serial configuration.
2. Midpoint Deviation:
- Introduced the midpoint deviation metric, offering insights into the balance and stability of the battery pack.
3. Additional Metrics:
- Consumed Ampere Hours: Tracking the total ampere hours consumed over time.
- Instantaneous Power: Providing real-time power consumption data for more …

Enhanced MQTT Data for Serial Battery Configuration

---

include/BatteryStats.h
lib/VeDirectFrameHandler/VeDirectData.cpp
src/BatteryStats.cpp
webapp/src/components/BatteryView.vue
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json
webapp/src/types/BatteryDataStatus.ts

This add the FW and HW version of a JK BMS to the card header in the live view like this:
It should add the FW version of a SmartShunt to the card as well (to be tested).

Feature: show BMS FW and HW version (JK BMS, SmartShunt)

---

include/Battery.h
include/JkBmsController.h
include/PinMapping.h
include/PowerMeter.h
include/SerialPortManager.h
include/VictronMppt.h
include/VictronSmartShunt.h
lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
lib/VeDirectFrameHandler/VeDirectFrameHandler.h
lib/VeDirectFrameHandler/VeDirectMpptController.cpp
lib/VeDirectFrameHandler/VeDirectMpptController.h
lib/VeDirectFrameHandler/VeDirectShuntController.cpp
lib/VeDirectFrameHandler/VeDirectShuntController.h
src/Battery.cpp
src/JkBmsController.cpp
src/PinMapping.cpp
src/PowerMeter.cpp
src/SerialPortManager.cpp
src/VictronMppt.cpp
src/VictronSmartShunt.cpp
src/WebApi_device.cpp
src/main.cpp

Still not using software based serial, this change makes the serial port manager assign a hardware serial port on a first-come-first-serve basis. All software components requiring a serial port now ask for the index to use at the serial port manager. There may be none left, such that a meaningful message is printed:
```
[SerialPortManager] HW UART 0 already in use by 'Victron MPPT 1'
[SerialPortManager] HW UART 1 already in use by 'Victron MPPT 2'
[SerialPortManager] HW UART 2 already in use by 'SDM power meter'
[SerialPortManager] Cannot assign another HW UART port to 'JK BMS'
```
ESP32 without USB CDC (all non-S3 and ESP32-S3 withouth USB CDC) still print their serial messages through hardware UART 0, so that one is reserved at initialization and only two hardware UARTs are freely …

Feature: Add support for a third Victron MPPT charge controller

---

include/MqttHandlePowerLimiter.h
src/MqttHandlePowerLimiter.cpp

As suggested in https://github.com/helgeerbe/OpenDTU-OnBattery/pull/1047#issuecomment-2170469378 TargetPowerConsumption can be set by sending a power value to topic 'powerlimiter/cmd/target_power_consumption' via MQTT and be read from topic 'powerlimiter/status/target_power_consumption'.
Is it correct that changing config values by issuing MQTT commands still entails writing to the flash memory (and thereby increasing the 'config save count')? 
A development goal is to keep and reflect (at some other place than the DPL settings menu) these changes independent of the flashed values?

Set/obtain DPL target power consumption via MQTT

---

include/BatteryCanReceiver.h
include/PylontechCanReceiver.h
src/BatteryCanReceiver.cpp
src/PylontechCanReceiver.cpp

I bought a Pytes V5 battery and even though it should talk 'Pylontech'-protocol via CAN its not 100% supported right now.
CAN messages look more like the BYD protocol: https://github.com/dfch/BydCanProtocol/tree/main?tab=readme-ov-file
To allow us to support different protocols i started to extract 'BatteryCanReceiver' as a a common base for all CAN batteries.
The main struggle right now is how we can keep the dummy data for the Pylontech working.
Please let me know if i went the right path with this and also if you have any idea how we can keep the dummy data working without ugly hacks.

feature: refactor PylontechCanBattery to be more generic

---

src/Utils.cpp

Gracefully handle numeric values that are disguised as a string in a JSON encoded message.
Closes #1104.

PowerMeter: handle JSON string values

---

lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp

Maximum buffer fill level when entering the VeDirectFrameHandler::loop()
Buffer size 256 Byte: 256 bytes 
Buffer size 512 Byte: 344 bytes  (maximum value, logged after 4 days)

Improvement: Double the VE.Direct receive buffer to 512 bytes to avoid overflow

---

src/WebApi_ws_live.cpp

the 2nd call was added in a merge operation in April

Removed double call to generateOnBatteryJsonResponse()

---

src/VictronMppt.cpp

Hallo @schlimmchen ,
in #975  wurde noch ein Problem entdeckt wenn mehrere Victron MPPTs konfiguriert wurden, aber mindestens einer keine Daten über die VE.Direct Schnittstelle sendet.
Das Problem ergibt sich aus der Kombination der Funktion VictronMpptClass::isDataValid() und einer weiteren wie VictronMpptClass::getOutputVoltage()
Die VictronMpptClass::getOutputVoltage()
liefert den kleinsten Wert aus der Menge an MPPTs die gültige Daten senden.
Die VictronMpptClass::isDataValid()
liefert nur true wenn **alle** konfigurierten MPPTs gültige Daten liefern.
Und wenn man das wie in der Funktion PowerLimiterClass::getBatteryVoltage() kombiniert 
float chargeControllerVoltage = -1;
if (VictronMppt.isDataValid()) {
res = chargeControllerVoltage = …

Fix an issue if not all configured MPPTs delivers valid Data

---

src/PowerMeterMqtt.cpp

* initialize values/memory
* protect all access to common memory with mutex
closes #1120.

MQTT powermeter fixes

---

include/MqttHandleHass.h
lib/Hoymiles/src/commands/ActivePowerControlCommand.cpp
src/MqttHandleHass.cpp
src/MqttHandleInverter.cpp
src/WebApi_limit.cpp
webapp/src/locales/index.ts
webapp/src/views/HomeView.vue

* when parsing a response from the inverter, preserve the accuracy when diving the integer value by 10.
* when processing web API limits, process them as float.
* when processing MQTT limits, process them as float.

Preserve Limit accuracy

---

include/MqttHandlePowerLimiterHass.h
include/PowerLimiter.h
src/MqttHandlePowerLimiter.cpp
src/MqttHandlePowerLimiterHass.cpp

Closes https://github.com/helgeerbe/OpenDTU-OnBattery/issues/996 by exposing full solar passthrough active via MQTT including HASS autodiscovery.
| HASS topic | state topic | HASS UI |
|-------------|-----------|----------|
|![Screenshot 2024-07-26 at 17 18 11](https://github.com/user-attachments/assets/e903b9fb-a124-480a-b5e1-5978dc8507a7)|![Screenshot 2024-07-26 at 17 18 01](https://github.com/user-attachments/assets/60e37759-02d5-40c7-9f62-5e72af926f42)|![Screenshot 2024-07-26 at 17 16 56](https://github.com/user-attachments/assets/6049dde2-9998-40cf-ba80-8e4cdfb5cde9)|

improvement: expose `full solar passsthrough active` via MQTT

---

include/BatteryStats.h
src/BatteryStats.cpp
src/PylontechCanReceiver.cpp
src/PytesCanReceiver.cpp
src/WebApi_ws_live.cpp
webapp/src/components/CardElement.vue
webapp/src/components/InverterTotalInfo.vue
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json
webapp/src/types/LiveDataStatus.ts

Resolves https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1129
- rename card title from `State of charge` to `Battery Charge`
- add `Battery Power` card
- show SoC, voltage, power and current if available
- move `_current` from individual implementations to `BatteryStats`
- add `_currentPrecision`
- use `_socPrecision` and `_currentPrecision` everywhere

improvement: show battery voltage and power in live view

---

include/Configuration.h
src/Configuration.cpp
src/MqttBattery.cpp
src/WebApi_battery.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json
webapp/src/types/BatteryConfig.ts
webapp/src/views/BatteryAdminView.vue

Implemented the - at least for my setup - missing unit for battery voltage received via MQTT. It compiles locally ~~, but could not test WebUI integration.~~ and was successfully tested on my Fusion board

Added unit for MQTT battery voltage

---

include/WebApi_firmware.h
src/WebApi_firmware.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json
webapp/src/types/FirmwareStatus.ts
webapp/src/views/FirmwareUpgradeView.vue

show a warning in the web UI that OTA updates are not supported, if they are not. this is the case when no second app partition is part of the partitioning scheme, which is determined by the firmware and communicated to the web app.

webapp: disable OTA firmware dialog for unsupported devices

---

webapp/src/views/AcChargerAdminView.vue

I don't see any harm by setting crazy numbers to target consumption, so i would say that we let him have it 🤷 
Resolves https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1154

adjust: remove ac-charger target consumption limits

---

src/BatteryStats.cpp

Precision is reduced to match the CAN protocol definition.
Current:
According to CAN protocol:

adjustment: reduce precision of charged- and discharged energy for pytes batteries

---

include/PowerLimiter.h
src/PowerLimiter.cpp

the switch "always start discharging battery at night" would cause to stop discharging the battery when there was solar power and the battery was discharged below the start threshold.
this change introduces a nighttime discharging boolean variable, which is enabled the instant we decide to start a battery discharge cycle due to nighttime havin arrived. we reset this variable as soon as it is daytime (solar power available). in that case, we allow discharging the battery if the start threshold was reached. this can actually be the case if the battery is charged with cheap electricity during the night.
removed comments as they merely spell out what the if statement already expresses quite nicely.
closes #1123.

Fix DPL nighttime discharging

---

.github/workflows/build.yml
README.md

disabled as uploading the changed gist failed repeatedly. maybe the token in secrets.GIST_SECRET has expired? need help from repo owner @helgeerbe to fix this.

disable "based on OpenDTU" badge

---

include/SPIPortManager.h
lib/CMT2300a/cmt2300a_hal.c
lib/CMT2300a/cmt2300a_hal.h
lib/CMT2300a/cmt2300wrapper.cpp
lib/CMT2300a/cmt2300wrapper.h
lib/CMT2300a/cmt_spi3.c
lib/CMT2300a/cmt_spi3.h
lib/Hoymiles/src/Hoymiles.cpp
lib/Hoymiles/src/Hoymiles.h
lib/Hoymiles/src/HoymilesRadio_CMT.cpp
lib/Hoymiles/src/HoymilesRadio_CMT.h
src/Huawei_can.cpp
src/InverterSettings.cpp
src/SPIPortManager.cpp
src/main.cpp

backport 'SPIPortManager' from skippermeisters fork: https://github.com/skippermeister/OpenDTU-OnBattery/commit/a642c9dbdb51d827cb7e709e58272ab682f4f680
Ongoing discussion: https://github.com/helgeerbe/OpenDTU-OnBattery/discussions/1132#discussioncomment-10174002
fixes: https://github.com/helgeerbe/OpenDTU-OnBattery/issues/605
~~- [ ] ESP32-C3 with NRF24 and CMT2300a~~
~~- [ ] ESP32-C3 with NRF24 and Huawei CAN~~
~~- [ ] ESP32-C3 with CMT2300a and Huawei CAN~~
| SPI # | SPI ID | SPI_HOST |
|--|--|--|
| 2     | 2      | 1        |
| 3     | 3      | 2        |
| SPI # | SPI ID | SPI_HOST |
|--|--|--|
| 2     | 0      | 1        |
| 3     | 1      | 2        |
| SPI # | SPI ID | SPI_HOST |
|--|--|--|
| 2     | 0      | 1        |

feature: SPIPortManager to allow use of CMT radio and Huawei charger at the same time

---

include/MqttHandleHuawei.h
include/MqttHandlePowerLimiter.h
src/MqttHandleHuawei.cpp
src/MqttHandlePowerLimiter.cpp
src/WebApi_mqtt.cpp

Update mqtt subscription and update homeassistant config when topic was changed.
Fixes https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1045

fix: update mqtt subscriptions when topic was changed

---

include/HttpGetter.h
include/PowerMeterHttpJson.h
src/HttpGetter.cpp

A user contacted me on discord (claims s(he) has no Github account) and told me that after upgrading to 2024.08.18, OpenDTU-OnBattery would no longer be able to fetch the power meter value from a Shelly 3 EM. That was a plausible claim as I already expected that the powermeter refactoring would not go without problems.
Even though nobody else came forward, which is strange, I investigated. It turns out that one optimization was illegal (according to HTTP standards): I started reusing the TCP connection to perform the second HTTP GET request after receiving an HTTP 401 (unauthorized) response in a setup with digest authentication. In general this is valid, but if the server sends "Connection: close" one must not reuse the TCP connection to perform any new request.
This is fixed by using …

Fix and improve HttpGetter (HTTP(S) + JSON power meter)

---

src/BatteryCanReceiver.cpp

we are running out of level 1 interrupts on ESP32-S3 boards. for that reason, until this prooves to be another sort of problem, we allocate the TWAI's interrupt for the battery CAN implementation at level 2.
closes #1164. relates to #1202.

Fix: Pylontech/Pytes CAN driver: user interrupts at level 2

---

include/BatteryStats.h
src/PowerLimiter.cpp
src/PylontechCanReceiver.cpp
src/PytesCanReceiver.cpp

Commit accc70dea0e4ead2f842f311d393530ad8fa0d55 added the battery SoC to the live view header. But due to getSoC returning an int the precision is currently limited.
This changes getSoC to return float so when a source with higher precision is available the full precision is shown.

Allow higher-resolution SoC in live view header

---

include/BatteryStats.h
src/BatteryStats.cpp
src/PylontechCanReceiver.cpp
src/PytesCanReceiver.cpp

If the string contains control characters for some reason, the browser will reject the json with the error `bad control character in string literal`.
See https://github.com/helgeerbe/OpenDTU-OnBattery/discussions/1226#discussioncomment-10566898

Sanitize manufacturer name to avoid json errors.

---

src/MqttHandleDtu.cpp
src/MqttHandleHass.cpp

I noticed that some useful ESP stats are missing on the MQTT feed, so this adds:
- ESP temperature
- ESP heap stats (size, free, minFree, maxAlloc)

Publish ESP heap and temperature details on Mqtt

---

src/MqttHandleHass.cpp

Fixes a copy and paste error in commit b3ee38b03ee3a8e2ed5d0b7accd104aa7c8b3a52 which I made when I renamed maxAlloc/minFree.

Fix typo in home-assistant discovery metadata

---

include/BatteryStats.h
src/BatteryStats.cpp
src/MqttHandleBatteryHass.cpp
src/PylontechCanReceiver.cpp

I noticed that these are missing while looking at dissassembly of the Pytes implementation of the protocol. I also found Pylontech sample CAN messages which match the Pytes implementation [1]:
```
CAN ID – followed by 2 to 8 bytes of data:
0x351 – 14 02 74 0E 74 0E CC 01 – Battery voltage + current limits
^^^^^ discharge cutoff voltage 46.0V
0x355 – 1A 00 64 00 – State of Health (SOH) / State of Charge (SOC)
0x356 – 02 13 00 00 4A 01 – Voltage / Current / Temp
0x359 – 00 00 00 00 0A 50 4E – Protection & Alarm flags
^^^^^ always 0x50 0x59 in Pytes implementation
^^ module count (matches the blog article image)
0x35C – C0 00 – Battery charge request flags
^^ two possible additional flags (bit 3 and bit 4)
0x35E – 50 59 4C 4F 4E 20 20 20 – Manufacturer name (“PYLON “)
^^^^^^^^^^^^^^ Note: …
```

Add additional Pylontech CAN protocol fields

---

webapp/vite.config.ts

Increased `chunkSizeWarningLimit` from 500k (default) to 1024k in order  to get rid of the warning messages. 
As the chunk is always larger than 500k, I assume, this does not hurt and the warning can be silenced

Increased chunkSizeWarningLimit

---

include/BatteryCanReceiver.h
include/BatteryStats.h
src/BatteryCanReceiver.cpp
src/BatteryStats.cpp
src/MqttHandleBatteryHass.cpp
src/PytesCanReceiver.cpp

The recently added PytesCanReceiver.cpp implements the Victron CAN protocol.
This change additionally adds support for the native Pytes CAN protocol messages.
Features only supported in Pytes protocol:
- High-resolution state of charge / full and remaining mAh
- Charge cycle counter
- Balancing state
Features only supported in Victron protocol:
- FW version
- Serial number
Note that the only known way to select the native Pytes protocol is via the serial console (Cisco-compatible cables work):
```
login config
setprt PYTES
logout
```
to return to Victron protocol use:
```
login config
setprt VICTRON
logout
```
The protocol switch will take effect immediately.
Tested on Pytes E-Box 4850
See https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1188

Pytes battery: Add support for native CAN protocol

---

src/WebApi_ws_vedirect_live.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json

I have integrated the battery temperature provided by the “Smart Battery Sense” into the web UI. The battery temperature is only displayed if a “Smart Battery Sense” or “BVM” is present and valid data is available.
Like on the Victron app the value will be displaced in °C without decimal places
Bugfix: Converting temperature from [K] to [°C]
Test cases: 
- Display on the web UI when the "Smart Battery Sense" is present (temperature displayed)
- Display on the web UI when the "Smart Battery Sense" is not present (temperature not displayed)
- Display on the web UI when the "Smart Battery Sense" fails during operation. (temperature disappears after 10 – 60 seconds)

Add battery temperature from "Smart Battery Sense" to Victron MPPT live view

---

src/HttpGetter.cpp

Due to power meter refactoring (#1077) a regression bug appeared, rendering the original bug (#612) useless.
Thx to @stefan123t for proposing a quick & easy fix by just swapping line 64 w/ line 65.
Fixes #1327

fix http power meter custom port regression bug

---

lib/Hoymiles/src/inverters/HERF_1CH.cpp
lib/Hoymiles/src/inverters/HERF_1CH.h
lib/Hoymiles/src/inverters/HERF_2CH.cpp
lib/Hoymiles/src/inverters/HERF_2CH.h
lib/Hoymiles/src/inverters/HMS_1CH.cpp
lib/Hoymiles/src/inverters/HMS_1CH.h
lib/Hoymiles/src/inverters/HMS_1CHv2.cpp
lib/Hoymiles/src/inverters/HMS_1CHv2.h
lib/Hoymiles/src/inverters/HMS_2CH.cpp
lib/Hoymiles/src/inverters/HMS_2CH.h
lib/Hoymiles/src/inverters/HMS_4CH.cpp
lib/Hoymiles/src/inverters/HMS_4CH.h
lib/Hoymiles/src/inverters/HMT_4CH.cpp
lib/Hoymiles/src/inverters/HMT_4CH.h
lib/Hoymiles/src/inverters/HMT_6CH.cpp
lib/Hoymiles/src/inverters/HMT_6CH.h
lib/Hoymiles/src/inverters/HM_1CH.cpp
lib/Hoymiles/src/inverters/HM_1CH.h
lib/Hoymiles/src/inverters/HM_2CH.cpp
lib/Hoymiles/src/inverters/HM_2CH.h
lib/Hoymiles/src/inverters/HM_4CH.cpp
lib/Hoymiles/src/inverters/HM_4CH.h
lib/Hoymiles/src/inverters/InverterAbstract.cpp
lib/Hoymiles/src/inverters/InverterAbstract.h
src/PowerLimiterInverter.cpp
src/PowerLimiterSolarInverter.cpp

This MR adds support for inverters, having multiple channels sharing one MPPT. This is achieved by combining all channels assigned to one MPPT before calculating any correction factors. The assignment between channels and MPPTs is added directly to the converter definition. For all inverters, that are already supported today, there should be no functional change, as the numb er of channels per MPPT is exactly one. The assignment of channel(s) to MPPT is currently calculated on every call - but I can also add some kind of caching for that.
If this approach is fine for you, I would try to get the changes of the Hoymiles library merged into the parent project.
I'm running custom build with these changes in my own setup (single HMT-2250) since a few days - and DPL seems to be stable. …

[DPL] Overscaling: Support for HMT inverters

---

src/PowerLimiterSolarInverter.cpp

As requested @schlimmchen i am providing changes to determine solar inverter maxIncrease based on shaded mppts.
I do have some open questions that i marked with TODO comments.
Please take a look and let me know what you think.

Feature: DPL: support for multiple inverters: solar inverter

---

include/VictronMppt.h
lib/VeDirectFrameHandler/VeDirectData.cpp
lib/VeDirectFrameHandler/VeDirectData.h
lib/VeDirectFrameHandler/VeDirectFrameHandler.h
lib/VeDirectFrameHandler/VeDirectFrameHexHandler.cpp
lib/VeDirectFrameHandler/VeDirectMpptController.cpp
lib/VeDirectFrameHandler/VeDirectMpptController.h
src/MqttHandleVedirect.cpp
src/MqttHandleVedirectHass.cpp
src/VictronMppt.cpp
src/WebApi_ws_vedirect_live.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json

PR includes the following:
- feature: read "absorption voltage" and "float voltage" from MPPTs
- extended: add some VE.Direct asynchronous messages descriptions
- extended: additional VictronMPPT class functions to get "MPPT-Mode", "absorption voltage" and "float voltage"
- bug fix: some HEX-Commands getting lost if we send to fast the next command
- correction of some typing errors

feature: get absorption- and float-voltage from MPPTs

---

lib/VeDirectFrameHandler/VeDirectData.h
lib/VeDirectFrameHandler/VeDirectMpptController.cpp
src/MqttHandleVedirect.cpp
src/MqttHandleVedirectHass.cpp
src/WebApi_ws_vedirect_live.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json

- add optional "load current" to live view, MQTT and HASS.
- change "load output" to optional handling
Charge controller with physical "load output" will publish "load output state" and "load current"
Charge controller without physical "load output" but configured "virtual output" will publish just "load output state"
Charge controller without physical "load output" and not configured "virtual output" will not publish "load output state" and "load current"

Add optional "load current" to live view, MQTT and HASS.

---

include/PowerLimiter.h
src/PowerLimiter.cpp

re-using the unconditional full solar-passthrough implementation does not work if the battery is full (full solar-passthrough active) while the grid consumption is higher than the solar output. we then only produce as much power as is available from the charge controllers, where we actually should match the grid cosumption using the battery's power.
notice that this makes "uncondictional full solar-passthrough" (the DPL mode of operation set through MQTT) something different than just "full solar-passthrough", as was before #1216.
closes #1422.

Fix: use battery when in full solar-passthrough

---

include/Huawei_can.h
src/Huawei_can.cpp

as shown in #1432, the Huawei AC charger sends signed values to communicate the temperature. given that the value range for all other data points is expected to be less than ~2 million, we now interpret all data as signed values.
Closes #1432.

Fix: Huawei AC charger sends signed values

---

src/PowerLimiter.cpp
src/SunPosition.cpp

Closes https://github.com/hoylabs/OpenDTU-OnBattery/issues/1407
I assumed that 'isSunsetAvailable' tells us if NTP is working and we got the correct time and timezone but actually it tells us if sunrise/sunset exists for the current timeperiod in the current timezone.

fix: wrong usage of 'isSunsetAvailable'

---

include/MqttBattery.h
src/MqttBattery.cpp

With this change we will allow users to set the decimal places (or precision) of the SoC when the MQTT Battery Provider is used.
|Live View|
|----------|
|![Screenshot 2024-12-07 at 18 53 43](https://github.com/user-attachments/assets/13d9d51a-a4af-42d2-ab94-52729f0269fd)|
Console 
```
18:56:32.934 > MqttBattery: Updated SoC to 49.93 from 'solarLights/battery/stateOfCharge'
18:56:33.076 > MqttBattery: Updated voltage to 52.68 from 'solarLights/battery/voltage'
...
18:56:51.454 > [DPL] battery interface enabled, SoC 49.9 % (used), age 3 s (valid)
18:56:51.462 > [DPL] BMS: 52.68 V, MPPT: -1.00 V, inverter 1164a00aaa1f: 52.80 
18:56:51.471 > [DPL] battery voltage 52.68 V, load-corrected voltage 52.68 V @ 0 W, factor 0.00130 1/A
```

Feature: auto-detect SoC precision for MQTT Battery provider

---

src/PowerLimiterSolarInverter.cpp

To prevent solar powered inverters from getting stuck at their limit because all MPPTs assume shaded we assume that we can increase the limit by 3% of the max power.
As discussed here: https://github.com/hoylabs/OpenDTU-OnBattery/pull/1473#issuecomment-2576016384
Test builds can be found here: https://github.com/hoylabs/OpenDTU-OnBattery/actions/runs/12667599063?pr=1507

Fix: assume small increase for shaded inverter

---

src/PowerLimiterSolarInverter.cpp

Fixes https://github.com/hoylabs/OpenDTU-OnBattery/issues/1512
Use inverter maxPower instead of configuredMaxPower for solar inverters with PDL to calculate the maxIncrease, because the limit will be distributed across MPPTs that can provide power by the inverter and not equally divided.
HMS-1600
2 out of 4 MPPTs connected
max output set to 800 W
current output power 400 W
maxTotalIncrease: `800 W - 400 W = 400 W`
max power per MPPT: `800 W / 4 = 200 W`
current power per non shaded MPPT: `400 W / 2 = 200 W`
max increase per non shaded MPPT: `200 W - 200 W = 0`
max increase:  `0 W * 2 = 0 W`
missed out increase (if PDL or overscaling is available): `400 W`
maxTotalIncrease: `800 W - 400 W = 400 W`
max power per MPPT: `1600 W / 4 = 400 W`
current power per non shaded MPPT: `400 W / 2 = 200 …

Fix: maxIncrease for solar inverter with PDL

---

src/gridcharger/huawei/Controller.cpp

the huawei grid charger's loop() uses the private method _setParameter() to update PSU settings. the loop() already holds the mutex, so _setParamater() must not try to lock the mutex again.
move the lock guard to the public setParameter() method, which resolves the issue.

Fix: huawei grid charger: prevent deadlock on mutex

---

src/PowerLimiterSolarInverter.cpp

Use inverter maxPower instead of configuredMaxPower when overscaling is enabled for a solar inverter to calculate the maxIncrease, because the limit will be overscaled to allow every MPPT to provide its maximum power.
Follow up to https://github.com/hoylabs/OpenDTU-OnBattery/pull/1513

Fix: maxIncrease for overscaling solar inverter

---

src/PowerLimiterSolarInverter.cpp
src/gridcharger/huawei/Controller.cpp

Merges branch development into master.

Prepare Release 2025.01.10

---

include/PowerLimiter.h
src/PowerLimiter.cpp

we do allow to send limit updates and to start or stop the inverter using the web UI or MQTT payloads or any other supported mean even if this inverter is governed by the DPL, while the DPL is disabled. this is also documented explicitly (see DPL mode MQTT docs).
after implementing support for multiple inverters, this behavior changed unintentionally. this changeset makes sure that inverters are shut down once when the DPL dis disabled, but are left alone afterwards for as long as the DPL is disabled.
closes #1521.

Fix: allow management of DPL inverters while DPL is off

---

include/BatteryStats.h
src/BatteryStats.cpp

Always show mqtt battery live view card as it provides the data age
Closes https://github.com/hoylabs/OpenDTU-OnBattery/issues/1540

Feature: show mqtt battery live view card

---

.github/workflows/build.yml
README.md

GIST_SECRET and the gist are living on my personal account as its not possible to have a gist on organisation level

Fix: 'create release badge' action 

---

src/PowerLimiterSolarInverter.cpp

Reverted as it leads to frequent, high changes of the limit on every other DPL loop.
Example: https://github.com/hoylabs/OpenDTU-OnBattery/discussions/1524
Original info that is true but can't be fixed with the rule that has been applied.
>Low limits
>Inverters with low limit (below 15%) are usually not able to provide the expected power and we would rate mppts as shaded.
>This will result in us thinking that we can't get more power from that inverter and the limit is 'stuck'.
Also reverts https://github.com/hoylabs/OpenDTU-OnBattery/pull/1507
Fixes https://github.com/hoylabs/OpenDTU-OnBattery/issues/1530

Fix: DPL limit is changing with every loop (solar-powered inverters)

---

src/VictronSmartShunt.cpp

Theoretically the battery provider "Smart Shunt" will stop providing data after 49 days.

fix: millis() rollover issue in smart shunt loop()

---

src/PowerLimiter.cpp

Make sure we only start a (nighttime) discharge cycle on a partially charged battery once during the night. This should be easy as the `_nighttimeDischarging` flag is already only reset at sunrise, so we "simply" have to NOT start another discharge cycle if the flag is already true.
Closes #1556.

Fix nighttime discharging starting multiple times during the night

---

.github/FUNDING.yml

The FUNDING.yml is used by github to show sponsorship links on the repository overview.

add schlimmchen to FUNDING.yml

---

include/gridcharger/huawei/HardwareInterface.h
src/gridcharger/huawei/HardwareInterface.cpp
src/gridcharger/huawei/MCP2515.cpp

* Fetching CAN messages (from the MCP2515) is very time critical. Attempt to miss less (hopefully none at all) messages.
* Stop caching new values for too long. Restore the previous trigger to push the values up to higher software levels.
* Send a request for data immediately after sending a parameter, allowing to update the PSU values in a timely manner.

Huawei grid charger usability fixes

---

include/solarcharger/DummyStats.h
include/solarcharger/Stats.h
include/solarcharger/mqtt/Stats.h
include/solarcharger/victron/Stats.h
src/solarcharger/victron/Stats.cpp

I'm not sure if I did it the right way.
I want to get the "State of Operation", "Float voltage" and "Absorption Voltage" from the victron charge controller.
But I don't want to force every solar charger provider to provide these functions.
If other provider (MPPT) support these functions, then other functions like the "Surplus" or the "Batterie Guard" should also work.
At least that was the idea behind. 
Any suggestions?

add: "State of Operation", "Float voltage" and "Absorption Voltage"

---

webapp/src/views/PowerLimiterAdminView.vue

This fixes that when a inverter was configured for overscaling with a firmware before PDL was introduced, then updated to a firmware that supports PDL you can still see the overscaling threshold input field in the DPL config.
w/o fix it looks like this

webapp: hide overscaling thresh. for inv with PDL

---

include/PowerLimiter.h
src/PowerLimiter.cpp

for smart-buffer-powered inverters, the unconditional full solar-passthrough implementation now sets the upper limit configured in the DPL settings.
To avoid confusion and to allow us to differentiate between the two modes/states the method 'fullSolarPassthrough' is now called 'unconditionalFullSolarPassthrough', which also better reflects its functionality.

Fix: DPL mode 2 for smart-buffer-powered inverters and unconditional-passthrough method name

---

include/solarcharger/Stats.h
src/solarcharger/victron/Stats.cpp

Changes:
- Removed case 246. This case is not used by solar charger, see Victron documentation for more details
- Add of unit information on function description
- Optional returning functions getYieldTotal() and getYieldDay() never return std::nullopt
- getPanelPowerWatts() cast explicit from float into int32_t and implizit from int32_t into uint16_t
currently no problem at all. Just to avoid problems in future.

Minor corrections: Solar charger - Victron

---

src/BatteryStats.cpp

use time stamp from frame handler instead time stamp from data transfer to battery stats.
We lose information on the way from "receiving data" to "work with data" and slow down regulation loops.
Actual I'm trying to calculate the "total solar panel power" from the "inverter power" + "battery power".
This will only work if the time stamp from both measurement devices fits together.

improvement: use time stamp from Victron frame handler 

---

include/battery/sbs/Stats.h
src/battery/sbs/Provider.cpp
src/battery/sbs/Stats.cpp

Align stats of SBS battery provider with other providers and use the shared 'setCurrent' method instead of maintaining its own field.
I discovered this while checking if there are timestamp differences possible between 'current' and 'voltage' in our batttery providers.

Fix: SBS battery: use Batteries::Stats setCurrent

---

src/PowerLimiterOverscalingInverter.cpp
src/PowerLimiterSmartBufferInverter.cpp

With the scaled limit we are not able to reduce the power as expected.
Closes #1665.

fix: DPL use current AC output for smart buffer reduction

---

include/PowerLimiter.h
include/PowerLimiterInverter.h
src/PowerLimiter.cpp
src/PowerLimiterInverter.cpp

the standby() method of battery- and smart-buffer-powered inverters only sets the inverter to actual standby. reaching that state can be checked for, so the update() method returns false (read: not busy) immediately if the inverter is already in standby.
on the other hand, solar-powered inverters update their limit to the configured minimum limit. testing for "is that limit already set" is not implemented and shall not be implemented. instead, we record a timestamp when starting the update, send the limit, and wait for it to complete before the update() method returns false, i.e., it never returns false on the first call.
DPL's reloadConfig() method relied on update() returning false immediately at some point to complete reloading the config. hence, that did not work when removing a …

Fix: cannot un-govern solar-powered inverters

---

include/PowerLimiterInverter.h
src/PowerLimiterInverter.cpp

once a limit command completes, we forget about it, even if it failed. this is a good choice since the limit value might be outdated once it timed out. the DPL shall calculate a new limit, which is then sent to the inverter instead.
we still retry power commands to shut down or wake up inverters as it is unlikely that the respective inverter shall have a different power state in the next DPL loop.
closes #1709.

Fix: do not retry limit commands

---

include/PowerLimiter.h
include/PowerLimiterInverter.h
src/PowerLimiter.cpp
src/PowerLimiterInverter.cpp

1. Fix: non-eligible inverters don't participate in achieving a new target output value in a particular DPL loop. however, we did not ignore them in calculations leading up to setting new limits. unreachable inverters were hence included in calculations with their last reported AC output value, which can be significant and is always ~10W for solar-powered inverters which went to sleep for the night.
2. Feature: instead of trying to calculate the household consumption, which is then used to calculate the desired total output of all DPL-governed inverters, we now enter a new DPL round with a target value ~~that is actually a difference~~ based on the power meter reading and eligible inverters alone: the eligible inverters shall produce whatever they produce now, but more or less the value …

Fix: DPL: ignore non-eligible inverters in every calculation

---

include/Configuration.h
include/powermeter/Provider.h
include/powermeter/udp/victron/Provider.h
src/Configuration.cpp
src/WebApi_powermeter.cpp
src/powermeter/Controller.cpp
src/powermeter/udp/victron/Provider.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/types/PowerMeterConfig.ts
webapp/src/views/PowerMeterAdminView.vue

This implements #1736 but does not close it, yet. I want this to be squashed as "Feature: Add support for Victron VM-3P75CT Power Meter" into Andreas' "use datapoints for powermeters" branch, and then mark his PR #1651 as closing the request.
Using cursor (the IDE) and having the respective experience what has to be added in what places, this was quite a fun excercise and took astonishingly little time. Also, thanks to @Sorbat's exploration and detailed feature request, it was possible to get this working on the very first try except for one little bug (6b999ea).

Feature: Add support for Victron VM-3P75CT Power Meter

---

include/Configuration.h
include/DataPoints.h
include/powermeter/DataPoints.h
include/powermeter/Provider.h
include/powermeter/json/http/Provider.h
include/powermeter/json/mqtt/Provider.h
include/powermeter/sdm/serial/Provider.h
include/powermeter/sml/Provider.h
include/powermeter/udp/smahm/Provider.h
include/powermeter/udp/victron/Provider.h
src/Configuration.cpp
src/WebApi_powermeter.cpp
src/powermeter/Controller.cpp
src/powermeter/Provider.cpp
src/powermeter/json/http/Provider.cpp
src/powermeter/json/mqtt/Provider.cpp
src/powermeter/sdm/serial/Provider.cpp
src/powermeter/sml/Provider.cpp
src/powermeter/sml/http/Provider.cpp
src/powermeter/udp/smahm/Provider.cpp
src/powermeter/udp/victron/Provider.cpp
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/types/PowerMeterConfig.ts
webapp/src/views/PowerMeterAdminView.vue

With this PR we switch all PowerMeter Providers to use DataPoints. This will allow us to easily build a HASS integration, show individual phase values in the LiveView and also to group inverters by phase within the DPL.
Additonaly i added reading the total power directly for 3-phase SDM powermeters as requested in issue https://github.com/hoylabs/OpenDTU-OnBattery/issues/765
~~https://github.com/hoylabs/OpenDTU-OnBattery/actions/runs/13398033363~~

Use DataPoints for all PowerMeter Providers

---

include/WebApi_ws_console.h
src/MessageOutput.cpp
src/WebApi_ws_console.cpp

I am done trying to figure out what goes wrong in some people's setups. Aviv/Sorbat and I are chatting about this from time to time for weeks now, but I am out of ideas.
However, what I can provide, is this changeset, which solves the worst part of the issue: The heap will not overrun any more and using the webconsole should therefore no longer cause unexpected reboots.
New approach: We move log message lines to the websocket clients individually. If any client's queue is full after adding the message line, we do the following:
1. Replace the last message with a warning that messages were dropped.
2. Drop all messages while the client's queue is full.
This works, as we no longer keep log lines indefinitely, expecting that all websocket clients will eventually process all messages. …

Fix webconsole heap issue

---

src/PowerLimiter.cpp

When the battery is requesting immediate charging we don't take any power from the DC bus and let the battery charge.
Closes #1771

Feature: DPL: respect immediate charging request

---

src/PowerLimiter.cpp
src/solarcharger/victron/Stats.cpp

For reasons/explanations, see new comments in changeset.
Closes #1762.

Fix: DPL: prevent underflow in solar charger output calculation

---

include/solarcharger/victron/Stats.h
lib/VeDirectFrameHandler/VeDirectFrameHandler.h
src/solarcharger/victron/Provider.cpp
src/solarcharger/victron/Stats.cpp

When data corruption happens we get phantom devices and the stats of those devices must be ignored when they get stale. The same applies to regular devices that stopped sending stats for whatever reason. Additionally we prevent phantom device stats to persist by using the connection setup defined `_logId` of the controller as the key to store the stats instead of the serial. (Thanks @ranma for the brilliant idea to solve this)
Related to https://github.com/hoylabs/OpenDTU-OnBattery/issues/1692
Makses #1778 obsolete.

Fix: Victron: ignore stale stats and prevent phantom device stats to persist

---

include/PowerLimiterInverter.h
src/PowerLimiterInverter.cpp

we currently rely on solar-powered inverters becoming unreachable during the night. they eventually do, but until they do, there is a (potentially) long stretch of time where they are unable to produce any power, i.e., they are in standby, but still reachable. in that case we don't know what the inverter would produce if it was woken up, so we assume it can produce its rated power. that is nonsense when it is dawn.
it seems that it is already "night" according to SunPosition when the inverter switches to standby on its own, we add tha respective check.
Closes #1759.

Fix: solar-powered inverters are non-eligible at nighttime

---

include/PowerLimiterOverscalingInverter.h
src/PowerLimiterBatteryInverter.cpp
src/PowerLimiterOverscalingInverter.cpp
src/PowerLimiterSmartBufferInverter.cpp
src/PowerLimiterSolarInverter.cpp

When overscaling is not in use we should make most decisions based on `getCurrentLimitWatts()`. Additionally the max increase is now constrained by the inverters max limit when overscaling is in use.

Improvement: DPL: improve handling without overscaling

---

src/PowerLimiter.cpp

as non-eligible inverters do not participate in the current DPL loop, we can and we should ignore whether or not we have current statistics on them. in particular this makes for unreachable inverters, which will not send stats for how ever long they are unreachable. the DPL shall not wait for those inverters to become reachable before continuing to do calculations, which ignore those inverters any way.
closes #1779.

Fix: ignore stats of non-eligible inverters

---

include/PowerLimiterInverter.h
src/PowerLimiter.cpp
src/PowerLimiterBatteryInverter.cpp
src/PowerLimiterInverter.cpp
src/PowerLimiterOverscalingInverter.cpp
src/PowerLimiterSmartBufferInverter.cpp
src/PowerLimiterSolarInverter.cpp

I looked at the use of `_inverters` in the DPL again to make sure `isEligible()` is called when needed. It seems we are fine now, except for unconditional solar passthrough.
In this context I noticed that we should not use an outdated voltage reading from an unreachable inverter.
Method `isEligible()` was simplified to do what the name suggests: return a boolean, which simplifies its usage.

Fix: inspect usage of isEligibile()

---

src/WebApi_dtu.cpp

Call `Hoymiles.setVerboseLoggin` when the config is saved via the web api.
Fixes #1741

Fix: en-/disable DTU verbose logging w/o restart

---

docs/DeviceProfiles/waveshare-esp32-s3-eth.json

A new device profile for the Waveshare ESP32-S3-ETH board.

add Waveshare ESP32-S3-ETH with ethernet

---

src/solarcharger/victron/Stats.cpp

Negative output power is possible for MPPTs with a load output, as they can draw electricity from both the solar input and the battery.
Resolves the concern raised by @SW-Niko: https://github.com/hoylabs/OpenDTU-OnBattery/pull/1817#issuecomment-2787194467

Fix: allow negative output power also when ve direct network input power is used

---

include/WebApi.h
include/WebApi_gridcharger.h
include/WebApi_ws_gridcharger.h
include/WebApi_ws_live.h
src/MqttHandleHuawei.cpp
src/WebApi.cpp
src/WebApi_gridcharger.cpp
src/WebApi_ws_gridcharger.cpp
src/WebApi_ws_live.cpp
webapp/src/components/HuaweiView.vue
webapp/src/components/InverterTotalInfo.vue
webapp/src/locales/de.json
webapp/src/locales/en.json
webapp/src/locales/fr.json
webapp/src/types/LiveDataStatus.ts
webapp/src/views/AcChargerAdminView.vue
webapp/src/views/HomeView.vue
webapp/vite.config.ts

This pull request focuses on renaming and refactoring the Huawei-related components to GridCharger components across various files. The most important changes include renaming classes, updating file names, and modifying API endpoints.
Renaming and refactoring:
* [`include/WebApi.h`](diffhunk://#diff-7e7cded3bc3ede892da59704e2a5f1b18110e2d3a6cea4ffcba26ed4747d5e79L32-R33): Replaced Huawei includes and class members with GridCharger equivalents. [[1]](diffhunk://#diff-7e7cded3bc3ede892da59704e2a5f1b18110e2d3a6cea4ffcba26ed4747d5e79L32-R33) [[2]](diffhunk://#diff-7e7cded3bc3ede892da59704e2a5f1b18110e2d3a6cea4ffcba26ed4747d5e79L84-R85)
* `include/WebApi_gridcharger.h` and `include/WebApi_ws_gridcharger.h`: Renamed from Huawei equivalents and updated class names. …

Improvement: rename huawei api endpoints

---

.github/workflows/build.yml

This step will post a comment on a PR with links to the firmware artifacts created by the build action of this PR. The comment will be updated when a new build was triggered.
I stumbled across [nightly.link](https://github.com/oprypin/nightly.link) and remembered that you can only download artifacts when logged in to github, additionally i thought that it might be cool to have a self updating comment on each PR that links to the latest build artifact.
Inspired by https://github.com/oprypin/nightly.link/blob/master/.github/workflows/pr-comment.yml
As you can see with the comment that github-actions posted below, it is getting updated with every run of the build step.
This pull request introduces a new workflow job in the `.github/workflows/build.yml` file to automatically comment on pull …

Improvement: workflow: automatically create comment with links to artifacts on pull-requests

---

.github/workflows/build.yml
.github/workflows/pr-artifacts-comment.yml

This is needed because a action run from a pull-requests coming from a fork does not have the required permissions to add and modify a comment. By splitting the workflows in two we can generate and store the comment data within the pull-request action and let another workflow run afterwards that has elevated permissions.

Fix: split artifacts comment in two workflows

---

lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
lib/VeDirectFrameHandler/VeDirectFrameHandler.h

This PR can be one possible solution of issue #1499 
Testing is ongoing on system with 1 smart shunt (2 frames) and 2 solar charger (1 frame) 
Note: isDataValid() use now the batteryVoltage_V_mV instead of the serialNr_SER because batteryVoltage_V_mV is available on all VE.Direct devices and serialNr_SER only on solar charger.

Improvement: Ve.Direct, FrameHandler, Handle timestamp of multiple frames

---

src/MqttHandlePowerLimiterHass.cpp

Fixing that UpperPowerLimit and TargetPowerConsumption are available via MQTT, but not auto discovered by Home Assistant.
see https://github.com/hoylabs/OpenDTU-OnBattery/issues/1178
So kann man durch eine einfache Home Assistant Automatisation das Target Tagsüber z.B. auf -400W setzen und nachts auf 0W damit nicht zu viel vom Akku eingespeist wird

Improvement: Add DPL settings HASS autodiscovery

---

include/gridcharger/huawei/Controller.h
include/gridcharger/huawei/DataPoints.h
include/gridcharger/huawei/HardwareInterface.h
include/gridcharger/huawei/MCP2515.h
include/gridcharger/huawei/TWAI.h
src/MqttHandleHuawei.cpp
src/WebApi_gridcharger.cpp
src/WebApi_ws_live.cpp
src/gridcharger/huawei/Controller.cpp
src/gridcharger/huawei/HardwareInterface.cpp
src/gridcharger/huawei/MCP2515.cpp
src/gridcharger/huawei/TWAI.cpp

@schlimmchen while i was working at making the GridCharger implementation generic I saw that the name Huawei is still used in a lot of places and that the namespace does not work for having `GridCharger` as the single controller name that should be used across the codebase.
Feel free to drop commits if you don't want them in you PR or close this PR if you don't want to increase the scope of your PR even further.
This pull request refactors the `GridCharger::Huawei` namespace and related classes to use a new namespace, `GridChargers::Huawei`, and renames the `Controller` class to `Provider`. It also updates all references to these changes across multiple files to ensure consistency.
* Updated the namespace from `GridCharger::Huawei` to `GridChargers::Huawei` in all relevant files, …

Huawei namespace and class naming

---

.github/workflows/build.yml

Closes #1931.
Tested in my fork: https://github.com/schlimmchen/OpenDTU-OnBattery/releases/tag/2025.05.03
Also tested: There is no error if `BADGE_GIST_ID` is not even set. The step is skipped as expected, without throwing an error.

Add release tag to release asset file names

---

lib/VeDirectFrameHandler/VeDirectData.cpp

Fix of #1945 
Life view will display "???" in case of multiple off reasons.
Tested with combination with:
- At night, No sun energy, OR = 0x00000001
- Charger off, Done with Victron app, OR = 0x00000004
Result:
[VE.Direct MPPT 11/12] Text Data 'OR' = '0X00000005'
Life view:

Fix:  get only the first off reason as readable text.

---

src/WebApi_logging.cpp

@tbnobody you might want to cherry pick this
This pull request includes a minor but important bug fix in the `WebApiLoggingClass::onLoggingAdminGet` method to ensure proper bounds checking for log module levels.
* [`src/WebApi_logging.cpp`](diffhunk://#diff-6b60c65749605006f05e8539fddeb5edea310c95d841db31a2f5e6231b3bddeeL45-R45): Updated the condition for determining the logging level to use `LOG_MODULE_COUNT` instead of `ESP_LOG_VERBOSE` for proper bounds checking. This ensures the index does not exceed the actual number of log modules.

webapp: fix: return log level for more than 5 modules

---

src/PowerLimiter.cpp

In https://github.com/hoylabs/OpenDTU-OnBattery/pull/1818, which was my previous attempt to fix this issue, i overlooked that hysteresis is used on line 651 to check if the new inverter limit should actually be set... with this fix i set hysteresis to 0 when inverters should be shutdown.

Fix: DPL: really ignore hysteresis when inverter should be shutdown

---

lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp

Was:
```
D (87704) veDirect: [[MPPT 10/9]] Text Data 'FW' = '164'
```
Now:
```
D (87704) veDirect: [MPPT 10/9] Text Data 'FW' = '164'
```
That's because the SUBTAG is already enclosed in square brackets.

Fix: remove duplicated square brackets from VE.Direct log messages

---

include/solarcharger/Stats.h
src/PowerLimiter.cpp
src/solarcharger/mqtt/Provider.cpp

Due to the load-output on solar chargers like the Victron 100/20 it is possible that the output_current and output_power are negative.
As discovered in https://github.com/hoylabs/OpenDTU-OnBattery/discussions/2139

SolarCharger: MQTT: accept negative values for output_current and output_power
